// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "swapi-api",
    "version": "1"
  },
  "paths": {
    "/api/characters": {
      "post": {
        "summary": "createCharacter",
        "description": "",
        "operationId": "createCharacter.post./api/characters",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "get": {
        "summary": "getCharacters",
        "description": "",
        "operationId": "getCharacters.get./api/characters",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/characters/{id}": {
      "get": {
        "summary": "getCharacter",
        "description": "",
        "operationId": "getCharacter.get./api/characters/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "updateCharacter",
        "description": "",
        "operationId": "updateCharacter.put./api/characters/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "deleteCharacter",
        "description": "",
        "operationId": "deleteCharacter.delete./api/characters/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/people": {
      "get": {
        "summary": "getAllPeople",
        "description": "",
        "operationId": "getAllPeople.get.api/people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/people/{id}": {
      "get": {
        "summary": "getPeopleById",
        "description": "",
        "operationId": "getPeopleById.get.api/people/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/people/search": {
      "get": {
        "summary": "searchPeople",
        "description": "",
        "operationId": "searchPeople.get.api/people/search",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "query",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/people/schema": {
      "get": {
        "summary": "getPeopleSchema",
        "description": "",
        "operationId": "getPeopleSchema.get.api/people/schema",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/films": {
      "get": {
        "summary": "getAllFilms",
        "description": "",
        "operationId": "getAllFilms.get.api/films",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/films/{id}": {
      "get": {
        "summary": "getFilmById",
        "description": "",
        "operationId": "getFilmById.get.api/films/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/films/search": {
      "get": {
        "summary": "searchFilms",
        "description": "",
        "operationId": "searchFilms.get.api/films/search",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "query",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/films/schema": {
      "get": {
        "summary": "getFilmsSchema",
        "description": "",
        "operationId": "getFilmsSchema.get.api/films/schema",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/starships": {
      "get": {
        "summary": "getAllStarships",
        "description": "",
        "operationId": "getAllStarships.get.api/starships",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/starships/{id}": {
      "get": {
        "summary": "getStarshipById",
        "description": "",
        "operationId": "getStarshipById.get.api/starships/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/starships/search": {
      "get": {
        "summary": "searchStarships",
        "description": "",
        "operationId": "searchStarships.get.api/starships/search",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "query",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/starships/schema": {
      "get": {
        "summary": "getStarshipsSchema",
        "description": "",
        "operationId": "getStarshipsSchema.get.api/starships/schema",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/species": {
      "get": {
        "summary": "getAllSpecies",
        "description": "",
        "operationId": "getAllSpecies.get.api/species",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/species/{id}": {
      "get": {
        "summary": "getSpeciesById",
        "description": "",
        "operationId": "getSpeciesById.get.api/species/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/species/search": {
      "get": {
        "summary": "searchSpecies",
        "description": "",
        "operationId": "searchSpecies.get.api/species/search",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "query",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/species/schema": {
      "get": {
        "summary": "getSpeciesSchema",
        "description": "",
        "operationId": "getSpeciesSchema.get.api/species/schema",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/vehicles": {
      "get": {
        "summary": "getAllVehicles",
        "description": "",
        "operationId": "getAllVehicles.get.api/vehicles",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/vehicles/{id}": {
      "get": {
        "summary": "getVehicleById",
        "description": "",
        "operationId": "getVehicleById.get.api/vehicles/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/vehicles/search": {
      "get": {
        "summary": "searchVehicles",
        "description": "",
        "operationId": "searchVehicles.get.api/vehicles/search",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "query",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/vehicles/schema": {
      "get": {
        "summary": "getVehiclesSchema",
        "description": "",
        "operationId": "getVehiclesSchema.get.api/vehicles/schema",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/planets": {
      "get": {
        "summary": "getAllPlanets",
        "description": "",
        "operationId": "getAllPlanets.get.api/planets",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/planets/{id}": {
      "get": {
        "summary": "getPlanetById",
        "description": "",
        "operationId": "getPlanetById.get.api/planets/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/planets/search": {
      "get": {
        "summary": "searchPlanets",
        "description": "",
        "operationId": "searchPlanets.get.api/planets/search",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "query",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/planets/schema": {
      "get": {
        "summary": "getPlanetsSchema",
        "description": "",
        "operationId": "getPlanetsSchema.get.api/planets/schema",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "APIResponse": {
      "properties": {
        "success": {
          "title": "APIResponse.success",
          "type": "boolean"
        },
        "data": {
          "title": "APIResponse.data"
        },
        "error": {
          "title": "APIResponse.error",
          "type": "string"
        }
      },
      "required": [
        "success"
      ],
      "additionalProperties": false,
      "title": "APIResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};